services:
  OxidEsales\EshopCommunity\Internal\Module\Install\MetadataTransferringServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Install\MetadataTransferringService
    autowire: true