services:
  OxidEsales\EshopCommunity\Internal\Module\Install\ModuleConfigurationInstallerInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Install\ModuleConfigurationInstaller
    autowire: true