imports:
   - { resource: Setup/services.yaml }
   - { resource: Configuration/services.yaml }
   - { resource: Cache/services.yaml }
   - { resource: TemplateExtension/services.yaml }
   - { resource: ShopModuleSetting/services.yaml }
   - { resource: State/services.yaml }
   - { resource: MetaData/services.yaml }
   - { resource: Install/service.yaml }
   - { resource: Command/services.yaml }
