services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Module\Bridge\ModuleListBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Bridge\ModuleListBridge

  OxidEsales\EshopCommunity\Internal\Module\Bridge\ModuleBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Bridge\ModuleBridge
